<Project ToolsVersion="15.0">
  
  <!-- SHARED REFERENCES -->
  <ItemGroup>
  	<PackageReference Include="P42.Serilog.QuickLog"  />
  </ItemGroup>
  <!-- PLATFORM SPECIFIC REFERENCES -->
  <ItemGroup Condition=" $(TargetFramework.Contains('windows')) ">
  </ItemGroup>
  <ItemGroup Condition=" !$(TargetFramework.Contains('windows')) ">
  </ItemGroup>
  <Choose>
    <When Condition="  $(MSBuildProjectName.ToLower().Contains('wasm'))  ">
      <ItemGroup>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
      </ItemGroup>
    </Otherwise>
  </Choose>




</Project>